setTimeout(()=>{console.log("I am ready, can start to work")}, 2000)
setTimeout(()=>{console.log("I am ready, can start to work")}, 2000)
setTimeout(()=>{console.log("I am ready, can start to work")}, 2000)
setTimeout(()=>{console.log("I am ready, can start to work")}, 2000)
setTimeout(()=>{console.log("I am ready, can start to work")}, 2000)
console.log("doing something in main thread")